# Site settings
title: Lexanne Painter
description: About Me
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Lexanne Painter
user_description: Experienced customer support technical lead for selfhosted data quality software implemented on distributed systems and Kubernetes clusters.
email: me@lexanne.io
# twitter_username: lorem_ipsum
#instagram_username:
#facebook_username: 
linkedin_username: lexanne
#github_username:  
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

head1: Test H1
head2_col1: Test H2 Col1
head2_col1_description: Test H2 Col1 Description
head2_col2: Test H2 Col2
head2_col2_description: Test H2 Col2 Description
head2_col3: Test H2 Col3
head2_col3_description: Test H2 Col3 Description



exclude: ['package.json', 'src', 'node_modules', 'vendor']

